/**
 * Achievement definitions for Казахский Дурак Онлайн.
 *
 * Rules:
 * - All achievements require <33.4% bots in the game (i.e., human-majority games).
 * - "Донатор" is an exception — it tracks shop purchases, not in-game events.
 * - "Первый шанырак" is triggered when ANY other achievement is first unlocked.
 */

export interface AchievementReward {
  shanyrak?: number;
  tenge?: number;
}

export interface AchievementDef {
  key: string;
  nameRu: string;
  nameKk: string;
  nameEn: string;
  descRu: string;
  descKk: string;
  descEn: string;
  reward: AchievementReward;
  /** Max progress value (for progress bar). 1 = binary unlock. */
  maxProgress: number;
  /** Category for grouping in UI */
  category: 'beginner' | 'combat' | 'special' | 'grind' | 'collector';
  /** Emoji icon */
  icon: string;
}

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    key: 'first_game',
    nameRu: 'Первый шаг',
    nameKk: 'Алғашқы қадам',
    nameEn: 'First Step',
    descRu: 'Сыграй первую партию с реальными людьми',
    descKk: 'Нақты адамдармен алғашқы ойынды ойна',
    descEn: 'Play your first game with real people',
    reward: { shanyrak: 500 },
    maxProgress: 1,
    category: 'beginner',
    icon: '🎯',
  },
  {
    key: 'steppe_student',
    nameRu: 'Степной ученик',
    nameKk: 'Дала шәкірті',
    nameEn: 'Steppe Student',
    descRu: 'Сыграй 10 партий',
    descKk: '10 ойын ойна',
    descEn: 'Play 10 games',
    reward: { shanyrak: 1000 },
    maxProgress: 10,
    category: 'grind',
    icon: '📚',
  },
  {
    key: 'golden_start',
    nameRu: 'Золотой старт',
    nameKk: 'Алтын бастама',
    nameEn: 'Golden Start',
    descRu: 'Набери 200 очков рейтинга',
    descKk: '200 рейтинг ұпайын жина',
    descEn: 'Reach 200 rating points',
    reward: { shanyrak: 1000 },
    maxProgress: 200,
    category: 'beginner',
    icon: '⭐',
  },
  {
    key: 'first_trump',
    nameRu: 'Первый козырь',
    nameKk: 'Алғашқы козырь',
    nameEn: 'First Trump',
    descRu: 'Побейся козырем в первой партии',
    descKk: 'Алғашқы ойында козырьмен жауап бер',
    descEn: 'Beat an attack with a trump card in your first game',
    reward: { shanyrak: 100 },
    maxProgress: 1,
    category: 'beginner',
    icon: '🃏',
  },
  {
    key: 'batyr_recruit',
    nameRu: 'Батыр-новобранец',
    nameKk: 'Батыр-жаңадан',
    nameEn: 'Batyr Recruit',
    descRu: 'Отбей 10 атак за одну партию',
    descKk: 'Бір ойында 10 шабуылды тойтар',
    descEn: 'Deflect 10 attacks in a single game',
    reward: { shanyrak: 500 },
    maxProgress: 1,
    category: 'combat',
    icon: '🛡️',
  },
  {
    key: 'bush_rabbit',
    nameRu: 'Заяц в кустах',
    nameKk: 'Бұтадағы қоян',
    nameEn: 'Bush Rabbit',
    descRu: 'Займи предпоследнее место в партии',
    descKk: 'Ойында соңғыдан бір алдыңғы орынды ал',
    descEn: 'Finish in second-to-last place in a game',
    reward: { shanyrak: 500 },
    maxProgress: 1,
    category: 'special',
    icon: '🐇',
  },
  {
    key: 'first_throw',
    nameRu: 'Первый подкид',
    nameKk: 'Алғашқы лақтыру',
    nameEn: 'First Throw',
    descRu: 'Подкинь 5 карт за один ход',
    descKk: 'Бір жүрісте 5 карта лақтыр',
    descEn: 'Throw 5 cards in a single turn',
    reward: { shanyrak: 300 },
    maxProgress: 1,
    category: 'combat',
    icon: '🎴',
  },
  {
    key: 'quick_win',
    nameRu: 'Быстрая победа',
    nameKk: 'Жылдам жеңіс',
    nameEn: 'Quick Win',
    descRu: 'Выиграй партию за 10 минут',
    descKk: 'Ойынды 10 минутта жеңіп шық',
    descEn: 'Win a game in under 10 minutes',
    reward: { shanyrak: 1500 },
    maxProgress: 1,
    category: 'combat',
    icon: '⚡',
  },
  {
    key: 'steppe_debut',
    nameRu: 'Степной дебют',
    nameKk: 'Дала дебюті',
    nameEn: 'Steppe Debut',
    descRu: 'Сыграй 50 партий',
    descKk: '50 ойын ойна',
    descEn: 'Play 50 games',
    reward: { shanyrak: 2000 },
    maxProgress: 50,
    category: 'grind',
    icon: '🏜️',
  },
  {
    key: 'little_hero',
    nameRu: 'Маленький герой',
    nameKk: 'Кішкентай батыр',
    nameEn: 'Little Hero',
    descRu: 'Отбей короля пики тузом пики',
    descKk: 'Пика королін пика тузымен жеңіп шық',
    descEn: 'Beat the King of Spades with the Ace of Spades',
    reward: { shanyrak: 500 },
    maxProgress: 1,
    category: 'special',
    icon: '🦸',
  },
  {
    key: 'first_berkut',
    nameRu: 'Первый беркут',
    nameKk: 'Алғашқы бүркіт',
    nameEn: 'First Berkut',
    descRu: 'Закончи партию с 1 картой на руках',
    descKk: 'Ойынды қолыңда 1 картамен аяқта',
    descEn: 'Finish a game with exactly 1 card in hand',
    reward: { shanyrak: 1000 },
    maxProgress: 1,
    category: 'special',
    icon: '🦅',
  },
  {
    key: 'first_shanyrak',
    nameRu: 'Первый шанырак',
    nameKk: 'Алғашқы шаңырақ',
    nameEn: 'First Shanyrak',
    descRu: 'Получи первое достижение',
    descKk: 'Алғашқы жетістікті ал',
    descEn: 'Unlock your first achievement',
    reward: { shanyrak: 200 },
    maxProgress: 1,
    category: 'beginner',
    icon: '🏠',
  },
  {
    key: 'three_throws',
    nameRu: 'Три подкида',
    nameKk: 'Үш лақтыру',
    nameEn: 'Triple Throw',
    descRu: 'Переведи ход 10 раз за одну партию',
    descKk: 'Бір ойында жүрісті 10 рет аудар',
    descEn: 'Transfer the attack 10 times in a single game',
    reward: { shanyrak: 800 },
    maxProgress: 1,
    category: 'combat',
    icon: '🔄',
  },
  {
    key: 'steppe_warrior',
    nameRu: 'Степной воин',
    nameKk: 'Дала жауынгері',
    nameEn: 'Steppe Warrior',
    descRu: 'Сыграй 100 партий',
    descKk: '100 ойын ойна',
    descEn: 'Play 100 games',
    reward: { shanyrak: 4000 },
    maxProgress: 100,
    category: 'grind',
    icon: '⚔️',
  },
  {
    key: 'trump_rookie',
    nameRu: 'Козырной новичок',
    nameKk: 'Козырь жаңадан',
    nameEn: 'Trump Rookie',
    descRu: 'Побей 20 карт козырем за одну партию',
    descKk: 'Бір ойында 20 картаны козырьмен жеңіп шық',
    descEn: 'Beat 20 cards with trumps in a single game',
    reward: { shanyrak: 1200 },
    maxProgress: 1,
    category: 'combat',
    icon: '👑',
  },
  {
    key: 'clean_win',
    nameRu: 'Чистая победа',
    nameKk: 'Таза жеңіс',
    nameEn: 'Clean Win',
    descRu: 'Выиграй партию, не взяв ни одной карты',
    descKk: 'Ойынды бірде-бір карта алмай жеңіп шық',
    descEn: 'Win a game without picking up any cards',
    reward: { shanyrak: 1500 },
    maxProgress: 1,
    category: 'combat',
    icon: '✨',
  },
  {
    key: 'quick_start',
    nameRu: 'Быстрый старт',
    nameKk: 'Жылдам старт',
    nameEn: 'Quick Start',
    descRu: 'Займи первое место 5 раз подряд',
    descKk: 'Қатарынан 5 рет бірінші орынды ал',
    descEn: 'Finish first 5 times in a row',
    reward: { shanyrak: 2000 },
    maxProgress: 5,
    category: 'grind',
    icon: '🚀',
  },
  {
    key: 'first_millionaire',
    nameRu: 'Первый миллионер',
    nameKk: 'Алғашқы миллионер',
    nameEn: 'First Millionaire',
    descRu: 'Накопи 1 000 000 шаныраков',
    descKk: '1 000 000 шаңырақ жина',
    descEn: 'Accumulate 1,000,000 shanyrak',
    reward: { shanyrak: 10000 },
    maxProgress: 1000000,
    category: 'collector',
    icon: '💰',
  },
  {
    key: 'donator',
    nameRu: 'Донатор',
    nameKk: 'Донатор',
    nameEn: 'Donator',
    descRu: 'Купи предметы в магазине на сумму более 100 Тенге',
    descKk: 'Дүкенде 100 Теңгеден астам тауар сатып ал',
    descEn: 'Purchase items in the shop for more than 100 Tenge',
    reward: { shanyrak: 5000, tenge: 20 },
    maxProgress: 100,
    category: 'collector',
    icon: '💎',
  },
  {
    key: 'spade_king',
    nameRu: 'Король пики',
    nameKk: 'Пика королі',
    nameEn: 'King of Spades',
    descRu: 'Побей козырной туз королём пики',
    descKk: 'Козырь тузын пика королімен жеңіп шық',
    descEn: 'Beat a trump ace with the King of Spades',
    reward: { shanyrak: 500 },
    maxProgress: 1,
    category: 'special',
    icon: '♠️',
  },
  {
    key: 'lucky_sevens',
    nameRu: 'Счастливые семёрки',
    nameKk: 'Бақытты жетілер',
    nameEn: 'Lucky Sevens',
    descRu: 'В конце матча начни ход, имея на руке только карту 777',
    descKk: 'Матч соңында тек 777 картасымен жүрісті баста',
    descEn: 'Start a turn with only the 777 card in hand at the end of a match',
    reward: { shanyrak: 2000 },
    maxProgress: 1,
    category: 'special',
    icon: '7️⃣',
  },
  {
    key: 'king_vs_777',
    nameRu: 'Король пики vs 777',
    nameKk: 'Пика королі vs 777',
    nameEn: 'King of Spades vs 777',
    descRu: 'Побей короля пики картой 777',
    descKk: 'Пика королін 777 картасымен жеңіп шық',
    descEn: 'Beat the King of Spades with the 777 card',
    reward: { shanyrak: 500 },
    maxProgress: 1,
    category: 'special',
    icon: '🃏',
  },
  {
    key: 'what_is_happening',
    nameRu: 'Что происходит?',
    nameKk: 'Не болып жатыр?',
    nameEn: 'What Is Happening?',
    descRu: 'Походи с 10-ки, перевернув ход игры',
    descKk: '10-шымен жүріп, ойын барысын өзгерт',
    descEn: 'Play a 10 and reverse the direction of play',
    reward: { shanyrak: 300 },
    maxProgress: 1,
    category: 'special',
    icon: '🔀',
  },
  {
    key: 'spiderman_meme',
    nameRu: 'Мем с человеком-пауком',
    nameKk: 'Өрмекші-адам мемі',
    nameEn: 'Spider-Man Meme',
    descRu: 'Переведи за один ход три раза подряд 10-ку на игрока, который походил с неё на тебя',
    descKk: 'Бір жүрісте 10-шыны саған жүрген ойыншыға үш рет қатарынан аудар',
    descEn: 'Transfer a 10 back to the player who played it on you, three times in a row in one turn',
    reward: { shanyrak: 1000 },
    maxProgress: 1,
    category: 'special',
    icon: '🕷️',
  },
];

export const ACHIEVEMENT_MAP: Record<string, AchievementDef> = Object.fromEntries(
  ACHIEVEMENTS.map(a => [a.key, a])
);

/** Bot ratio threshold — achievements only count if bots < this fraction */
export const MAX_BOT_RATIO = 1 / 3; // 33.4%
