/**
 * Achievement definitions for Казахский Дурак Онлайн.
 *
 * Rules:
 * - All achievements require <33.4% bots in the game (i.e., human-majority games).
 * - "Донатор" is an exception — it tracks shop purchases, not in-game events.
 * - "Первый шанырак" is triggered when ANY other achievement is first unlocked.
 */

export interface AchievementReward {
  shanyrak?: number;
  tenge?: number;
}

export interface AchievementDef {
  key: string;
  nameRu: string;
  nameKk: string;
  nameEn: string;
  descRu: string;
  descKk: string;
  descEn: string;
  reward: AchievementReward;
  /** Max progress value (for progress bar). 1 = binary unlock. */
  maxProgress: number;
  /** Category for grouping in UI */
  category: 'beginner' | 'combat' | 'special' | 'grind' | 'collector' | 'premium' | 'season' | 'social';
  /** Emoji icon */
  icon: string;
}

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    key: 'first_game',
    nameRu: 'Первый шаг',
    nameKk: 'Алғашқы қадам',
    nameEn: 'First Step',
    descRu: 'Сыграй первую партию с реальными людьми',
    descKk: 'Нақты адамдармен алғашқы ойынды ойна',
    descEn: 'Play your first game with real people',
    reward: { shanyrak: 500 },
    maxProgress: 1,
    category: 'beginner',
    icon: '🎯',
  },
  {
    key: 'steppe_student',
    nameRu: 'Степной ученик',
    nameKk: 'Дала шәкірті',
    nameEn: 'Steppe Student',
    descRu: 'Сыграй 10 партий',
    descKk: '10 ойын ойна',
    descEn: 'Play 10 games',
    reward: { shanyrak: 1000 },
    maxProgress: 10,
    category: 'grind',
    icon: '📚',
  },
  {
    key: 'golden_start',
    nameRu: 'Золотой старт',
    nameKk: 'Алтын бастама',
    nameEn: 'Golden Start',
    descRu: 'Набери 1200 очков рейтинга',
    descKk: '1200 рейтинг ұпайын жина',
    descEn: 'Reach 1200 rating points',
    reward: { shanyrak: 1000 },
    maxProgress: 1200,
    category: 'beginner',
    icon: '⭐',
  },
  {
    key: 'first_trump',
    nameRu: 'Первый козырь',
    nameKk: 'Алғашқы козырь',
    nameEn: 'First Trump',
    descRu: 'Побейся козырем в первой партии',
    descKk: 'Алғашқы ойында козырьмен жауап бер',
    descEn: 'Beat an attack with a trump card in your first game',
    reward: { shanyrak: 100 },
    maxProgress: 1,
    category: 'beginner',
    icon: '🃏',
  },
  {
    key: 'batyr_recruit',
    nameRu: 'Батыр-новобранец',
    nameKk: 'Батыр-жаңадан',
    nameEn: 'Batyr Recruit',
    descRu: 'Отбей 10 атак за одну партию',
    descKk: 'Бір ойында 10 шабуылды тойтар',
    descEn: 'Deflect 10 attacks in a single game',
    reward: { shanyrak: 500 },
    maxProgress: 1,
    category: 'combat',
    icon: '🛡️',
  },
  {
    key: 'bush_rabbit',
    nameRu: 'Заяц в кустах',
    nameKk: 'Бұтадағы қоян',
    nameEn: 'Bush Rabbit',
    descRu: 'Займи предпоследнее место в партии',
    descKk: 'Ойында соңғыдан бір алдыңғы орынды ал',
    descEn: 'Finish in second-to-last place in a game',
    reward: { shanyrak: 500 },
    maxProgress: 1,
    category: 'special',
    icon: '🐇',
  },
  {
    key: 'first_throw',
    nameRu: 'Первый подкид',
    nameKk: 'Алғашқы лақтыру',
    nameEn: 'First Throw',
    descRu: 'Подкинь 5 карт за один ход',
    descKk: 'Бір жүрісте 5 карта лақтыр',
    descEn: 'Throw 5 cards in a single turn',
    reward: { shanyrak: 300 },
    maxProgress: 1,
    category: 'combat',
    icon: '🎴',
  },
  {
    key: 'quick_win',
    nameRu: 'Быстрая победа',
    nameKk: 'Жылдам жеңіс',
    nameEn: 'Quick Win',
    descRu: 'Выиграй партию за 10 минут',
    descKk: 'Ойынды 10 минутта жеңіп шық',
    descEn: 'Win a game in under 10 minutes',
    reward: { shanyrak: 1500 },
    maxProgress: 1,
    category: 'combat',
    icon: '⚡',
  },
  {
    key: 'steppe_debut',
    nameRu: 'Степной дебют',
    nameKk: 'Дала дебюті',
    nameEn: 'Steppe Debut',
    descRu: 'Сыграй 50 партий',
    descKk: '50 ойын ойна',
    descEn: 'Play 50 games',
    reward: { shanyrak: 2000 },
    maxProgress: 50,
    category: 'grind',
    icon: '🏜️',
  },
  {
    key: 'little_hero',
    nameRu: 'Маленький герой',
    nameKk: 'Кішкентай батыр',
    nameEn: 'Little Hero',
    descRu: 'Отбей короля пики тузом пики',
    descKk: 'Пика королін пика тузымен жеңіп шық',
    descEn: 'Beat the King of Spades with the Ace of Spades',
    reward: { shanyrak: 500 },
    maxProgress: 1,
    category: 'special',
    icon: '🦸',
  },
  {
    key: 'first_berkut',
    nameRu: 'Первый беркут',
    nameKk: 'Алғашқы бүркіт',
    nameEn: 'First Berkut',
    descRu: 'Закончи партию с 1 картой на руках',
    descKk: 'Ойынды қолыңда 1 картамен аяқта',
    descEn: 'Finish a game with exactly 1 card in hand',
    reward: { shanyrak: 1000 },
    maxProgress: 1,
    category: 'special',
    icon: '🦅',
  },
  {
    key: 'first_shanyrak',
    nameRu: 'Первый шанырак',
    nameKk: 'Алғашқы шаңырақ',
    nameEn: 'First Shanyrak',
    descRu: 'Получи первое достижение',
    descKk: 'Алғашқы жетістікті ал',
    descEn: 'Unlock your first achievement',
    reward: { shanyrak: 200 },
    maxProgress: 1,
    category: 'beginner',
    icon: '🏠',
  },
  {
    key: 'three_throws',
    nameRu: 'Три подкида',
    nameKk: 'Үш лақтыру',
    nameEn: 'Triple Throw',
    descRu: 'Переведи ход 10 раз за одну партию',
    descKk: 'Бір ойында жүрісті 10 рет аудар',
    descEn: 'Transfer the attack 10 times in a single game',
    reward: { shanyrak: 800 },
    maxProgress: 1,
    category: 'combat',
    icon: '🔄',
  },
  {
    key: 'steppe_warrior',
    nameRu: 'Степной воин',
    nameKk: 'Дала жауынгері',
    nameEn: 'Steppe Warrior',
    descRu: 'Сыграй 100 партий',
    descKk: '100 ойын ойна',
    descEn: 'Play 100 games',
    reward: { shanyrak: 4000 },
    maxProgress: 100,
    category: 'grind',
    icon: '⚔️',
  },
  {
    key: 'trump_rookie',
    nameRu: 'Козырной новичок',
    nameKk: 'Козырь жаңадан',
    nameEn: 'Trump Rookie',
    descRu: 'Побей 20 карт козырем за одну партию',
    descKk: 'Бір ойында 20 картаны козырьмен жеңіп шық',
    descEn: 'Beat 20 cards with trumps in a single game',
    reward: { shanyrak: 1200 },
    maxProgress: 1,
    category: 'combat',
    icon: '👑',
  },
  {
    key: 'clean_win',
    nameRu: 'Чистая победа',
    nameKk: 'Таза жеңіс',
    nameEn: 'Clean Win',
    descRu: 'Выиграй партию, не взяв ни одной карты',
    descKk: 'Ойынды бірде-бір карта алмай жеңіп шық',
    descEn: 'Win a game without picking up any cards',
    reward: { shanyrak: 1500 },
    maxProgress: 1,
    category: 'combat',
    icon: '✨',
  },
  {
    key: 'quick_start',
    nameRu: 'Быстрый старт',
    nameKk: 'Жылдам старт',
    nameEn: 'Quick Start',
    descRu: 'Займи первое место 5 раз подряд',
    descKk: 'Қатарынан 5 рет бірінші орынды ал',
    descEn: 'Finish first 5 times in a row',
    reward: { shanyrak: 2000 },
    maxProgress: 5,
    category: 'grind',
    icon: '🚀',
  },
  {
    key: 'first_millionaire',
    nameRu: 'Первый миллионер',
    nameKk: 'Алғашқы миллионер',
    nameEn: 'First Millionaire',
    descRu: 'Накопи 1 000 000 шаныраков',
    descKk: '1 000 000 шаңырақ жина',
    descEn: 'Accumulate 1,000,000 shanyrak',
    reward: { shanyrak: 10000 },
    maxProgress: 1000000,
    category: 'collector',
    icon: '💰',
  },
  {
    key: 'donator',
    nameRu: 'Донатор',
    nameKk: 'Донатор',
    nameEn: 'Donator',
    descRu: 'Купи предметы в магазине на сумму более 100 Тенге',
    descKk: 'Дүкенде 100 Теңгеден астам тауар сатып ал',
    descEn: 'Purchase items in the shop for more than 100 Tenge',
    reward: { shanyrak: 5000, tenge: 20 },
    maxProgress: 100,
    category: 'collector',
    icon: '💎',
  },
  {
    key: 'spade_king',
    nameRu: 'Король пики',
    nameKk: 'Пика королі',
    nameEn: 'King of Spades',
    descRu: 'Побей козырной туз королём пики',
    descKk: 'Козырь тузын пика королімен жеңіп шық',
    descEn: 'Beat a trump ace with the King of Spades',
    reward: { shanyrak: 500 },
    maxProgress: 1,
    category: 'special',
    icon: '♠️',
  },
  {
    key: 'lucky_sevens',
    nameRu: 'Счастливые семёрки',
    nameKk: 'Бақытты жетілер',
    nameEn: 'Lucky Sevens',
    descRu: 'В конце матча начни ход, имея на руке только карту 777',
    descKk: 'Матч соңында тек 777 картасымен жүрісті баста',
    descEn: 'Start a turn with only the 777 card in hand at the end of a match',
    reward: { shanyrak: 2000 },
    maxProgress: 1,
    category: 'special',
    icon: '7️⃣',
  },
  {
    key: 'king_vs_777',
    nameRu: 'Король пики vs 777',
    nameKk: 'Пика королі vs 777',
    nameEn: 'King of Spades vs 777',
    descRu: 'Побей короля пики картой 777',
    descKk: 'Пика королін 777 картасымен жеңіп шық',
    descEn: 'Beat the King of Spades with the 777 card',
    reward: { shanyrak: 500 },
    maxProgress: 1,
    category: 'special',
    icon: '🃏',
  },
  {
    key: 'what_is_happening',
    nameRu: 'Что происходит?',
    nameKk: 'Не болып жатыр?',
    nameEn: 'What Is Happening?',
    descRu: 'Походи с 10-ки, перевернув ход игры',
    descKk: '10-шымен жүріп, ойын барысын өзгерт',
    descEn: 'Play a 10 and reverse the direction of play',
    reward: { shanyrak: 300 },
    maxProgress: 1,
    category: 'special',
    icon: '🔀',
  },
  {
    key: 'spiderman_meme',
    nameRu: 'Мем с человеком-пауком',
    nameKk: 'Өрмекші-адам мемі',
    nameEn: 'Spider-Man Meme',
    descRu: 'Переведи за один ход три раза подряд 10-ку на игрока, который походил с неё на тебя',
    descKk: 'Бір жүрісте 10-шыны саған жүрген ойыншыға үш рет қатарынан аудар',
    descEn: 'Transfer a 10 back to the player who played it on you, three times in a row in one turn',
    reward: { shanyrak: 1000 },
    maxProgress: 1,
    category: 'special',
    icon: '🕷️',
  },

  // ============================================================
  // PREMIUM achievements (1-5)
  // ============================================================
  {
    key: 'premium_player',
    nameRu: 'Премиум игрок',
    nameKk: 'Premium ойыншы',
    nameEn: 'Premium Player',
    descRu: 'Приобретите PREMIUM хотя бы один раз',
    descKk: 'PREMIUM-ді кемінде бір рет сатып алыңыз',
    descEn: 'Purchase PREMIUM at least once',
    reward: { shanyrak: 5000, tenge: 25 },
    maxProgress: 1,
    category: 'premium',
    icon: '💎',
  },
  {
    key: 'legendary_player',
    nameRu: 'Легендарный игрок',
    nameKk: 'Аңыздық ойыншы',
    nameEn: 'Legendary Player',
    descRu: 'Приобретите PREMIUM два месяца подряд',
    descKk: 'PREMIUM-ді қатарынан екі ай сатып алыңыз',
    descEn: 'Purchase PREMIUM two months in a row',
    reward: { shanyrak: 15000, tenge: 50 },
    maxProgress: 2,
    category: 'premium',
    icon: '🌟',
  },
  {
    key: 'admin_pryanik',
    nameRu: 'Админу пряников',
    nameKk: 'Әкімшіге тәттілер',
    nameEn: 'Gingerbread for Admin',
    descRu: 'Приобретите PREMIUM три месяца подряд',
    descKk: 'PREMIUM-ді қатарынан үш ай сатып алыңыз',
    descEn: 'Purchase PREMIUM three months in a row',
    reward: { shanyrak: 30000, tenge: 100 },
    maxProgress: 3,
    category: 'premium',
    icon: '🍪',
  },
  {
    key: 'kazakhstan_pride',
    nameRu: 'Гордость Казахстана',
    nameKk: 'Қазақстан мақтанышы',
    nameEn: 'Pride of Kazakhstan',
    descRu: 'Приобретите PREMIUM шесть месяцев подряд',
    descKk: 'PREMIUM-ді қатарынан алты ай сатып алыңыз',
    descEn: 'Purchase PREMIUM six months in a row',
    reward: { shanyrak: 100000, tenge: 500 },
    maxProgress: 6,
    category: 'premium',
    icon: '🇰🇿',
  },
  {
    key: 'elbasy',
    nameRu: 'Елбасы',
    nameKk: 'Елбасы',
    nameEn: 'Elbasy',
    descRu: 'Приобретите PREMIUM 10 раз (не обязательно подряд)',
    descKk: 'PREMIUM-ді 10 рет сатып алыңыз (қатарынан болмауы мүмкін)',
    descEn: 'Purchase PREMIUM 10 times (not necessarily in a row)',
    reward: { shanyrak: 777777, tenge: 777 },
    maxProgress: 10,
    category: 'premium',
    icon: '👑',
  },

  // ============================================================
  // DAILY QUEST achievements (6-8)
  // ============================================================
  {
    key: 'daily_diary',
    nameRu: 'Ежедневник',
    nameKk: 'Күнделік',
    nameEn: 'Daily Diary',
    descRu: 'Выполните 30 ежедневных заданий',
    descKk: '30 күнделікті тапсырма орындаңыз',
    descEn: 'Complete 30 daily quests',
    reward: { shanyrak: 3000 },
    maxProgress: 30,
    category: 'grind',
    icon: '📓',
  },
  {
    key: 'daily_calendar',
    nameRu: 'Календарь',
    nameKk: 'Күнтізбе',
    nameEn: 'Calendar',
    descRu: 'Выполните 60 ежедневных заданий',
    descKk: '60 күнделікті тапсырма орындаңыз',
    descEn: 'Complete 60 daily quests',
    reward: { shanyrak: 10000 },
    maxProgress: 60,
    category: 'grind',
    icon: '📅',
  },
  {
    key: 'daily_regular',
    nameRu: 'Постоянник',
    nameKk: 'Тұрақты ойыншы',
    nameEn: 'Regular',
    descRu: 'Выполните 120 ежедневных заданий',
    descKk: '120 күнделікті тапсырма орындаңыз',
    descEn: 'Complete 120 daily quests',
    reward: { shanyrak: 30000 },
    maxProgress: 120,
    category: 'grind',
    icon: '🗓️',
  },

  // ============================================================
  // ACHIEVEMENT COUNT achievements (9-12)
  // ============================================================
  {
    key: 'achievement_lover',
    nameRu: 'Любитель',
    nameKk: 'Сүйіспеншілік',
    nameEn: 'Enthusiast',
    descRu: 'Выполните 10 любых достижений',
    descKk: 'Кез келген 10 жетістікті орындаңыз',
    descEn: 'Unlock any 10 achievements',
    reward: { shanyrak: 5000 },
    maxProgress: 10,
    category: 'collector',
    icon: '🏅',
  },
  {
    key: 'achievement_expert',
    nameRu: 'Эксперт',
    nameKk: 'Сарапшы',
    nameEn: 'Expert',
    descRu: 'Выполните 20 любых достижений',
    descKk: 'Кез келген 20 жетістікті орындаңыз',
    descEn: 'Unlock any 20 achievements',
    reward: { shanyrak: 8000 },
    maxProgress: 20,
    category: 'collector',
    icon: '🥈',
  },
  {
    key: 'achievement_master',
    nameRu: 'Мастер',
    nameKk: 'Шебер',
    nameEn: 'Master',
    descRu: 'Выполните 30 любых достижений',
    descKk: 'Кез келген 30 жетістікті орындаңыз',
    descEn: 'Unlock any 30 achievements',
    reward: { shanyrak: 10000 },
    maxProgress: 30,
    category: 'collector',
    icon: '🥇',
  },
  {
    key: 'achievement_achiever',
    nameRu: 'Достигатор',
    nameKk: 'Жетістікші',
    nameEn: 'Achiever',
    descRu: 'Выполните 50 любых достижений',
    descKk: 'Кез келген 50 жетістікті орындаңыз',
    descEn: 'Unlock any 50 achievements',
    reward: { shanyrak: 50000, tenge: 25 },
    maxProgress: 50,
    category: 'collector',
    icon: '🏆',
  },

  // ============================================================
  // COLLECTOR achievements (13-16)
  // ============================================================
  {
    key: 'fashionista',
    nameRu: 'Модник',
    nameKk: 'Сәнқой',
    nameEn: 'Fashionista',
    descRu: 'Получите как минимум 3 разные рамки для аватарки',
    descKk: 'Кемінде 3 түрлі аватар жақтауын алыңыз',
    descEn: 'Obtain at least 3 different avatar frames',
    reward: { shanyrak: 10000, tenge: 25 },
    maxProgress: 3,
    category: 'collector',
    icon: '🖼️',
  },
  {
    key: 'croupier',
    nameRu: 'Крупье',
    nameKk: 'Крупье',
    nameEn: 'Croupier',
    descRu: 'Получите как минимум 3 разные колоды карт (не считая классическую)',
    descKk: 'Кемінде 3 түрлі карта дестесін алыңыз (классикалықты есептемегенде)',
    descEn: 'Obtain at least 3 different card decks (excluding the classic)',
    reward: { shanyrak: 10000, tenge: 25 },
    maxProgress: 3,
    category: 'collector',
    icon: '🃏',
  },
  {
    key: 'meloman',
    nameRu: 'Меломан',
    nameKk: 'Меломан',
    nameEn: 'Meloman',
    descRu: 'Получите как минимум 3 разных плейлиста (не считая классический)',
    descKk: 'Кемінде 3 түрлі ойнату тізімін алыңыз (классикалықты есептемегенде)',
    descEn: 'Obtain at least 3 different playlists (excluding the classic)',
    reward: { shanyrak: 10000 },
    maxProgress: 3,
    category: 'collector',
    icon: '🎵',
  },
  {
    key: 'many_faces',
    nameRu: 'Многоликий',
    nameKk: 'Көпбейнелі',
    nameEn: 'Many Faces',
    descRu: 'Получите как минимум 5 разных аватарок (не считая классических)',
    descKk: 'Кемінде 5 түрлі аватар алыңыз (классикалықтарды есептемегенде)',
    descEn: 'Obtain at least 5 different avatars (excluding the classic ones)',
    reward: { shanyrak: 10000, tenge: 10 },
    maxProgress: 5,
    category: 'collector',
    icon: '🎭',
  },

  // ============================================================
  // SEASON RANK achievements (17-24)
  // ============================================================
  {
    key: 'season_steppe_hare',
    nameRu: 'Степной заяц',
    nameKk: 'Дала қояны',
    nameEn: 'Steppe Hare',
    descRu: 'Закончите сезон с рангом «Степной заяц»',
    descKk: 'Сезонды «Дала қояны» дәрежесімен аяқтаңыз',
    descEn: 'Finish a season with the rank Steppe Hare',
    reward: { shanyrak: 1000 },
    maxProgress: 1,
    category: 'season',
    icon: '🐇',
  },
  {
    key: 'season_mountain_ram',
    nameRu: 'Горный баран',
    nameKk: 'Тау қошқары',
    nameEn: 'Mountain Ram',
    descRu: 'Закончите сезон с рангом «Горный баран»',
    descKk: 'Сезонды «Тау қошқары» дәрежесімен аяқтаңыз',
    descEn: 'Finish a season with the rank Mountain Ram',
    reward: { shanyrak: 2000 },
    maxProgress: 1,
    category: 'season',
    icon: '🐏',
  },
  {
    key: 'season_golden_falcon',
    nameRu: 'Золотой сокол',
    nameKk: 'Алтын сұңқар',
    nameEn: 'Golden Falcon',
    descRu: 'Закончите сезон с рангом «Золотой сокол»',
    descKk: 'Сезонды «Алтын сұңқар» дәрежесімен аяқтаңыз',
    descEn: 'Finish a season with the rank Golden Falcon',
    reward: { shanyrak: 3000 },
    maxProgress: 1,
    category: 'season',
    icon: '🦅',
  },
  {
    key: 'season_winged_horse',
    nameRu: 'Крылатый конь',
    nameKk: 'Қанатты жылқы',
    nameEn: 'Winged Horse',
    descRu: 'Закончите сезон с рангом «Крылатый конь»',
    descKk: 'Сезонды «Қанатты жылқы» дәрежесімен аяқтаңыз',
    descEn: 'Finish a season with the rank Winged Horse',
    reward: { shanyrak: 4000 },
    maxProgress: 1,
    category: 'season',
    icon: '🐎',
  },
  {
    key: 'season_sky_eagle',
    nameRu: 'Небесный орел',
    nameKk: 'Аспан бүркіті',
    nameEn: 'Sky Eagle',
    descRu: 'Закончите сезон с рангом «Небесный орел»',
    descKk: 'Сезонды «Аспан бүркіті» дәрежесімен аяқтаңыз',
    descEn: 'Finish a season with the rank Sky Eagle',
    reward: { shanyrak: 5000 },
    maxProgress: 1,
    category: 'season',
    icon: '🦅',
  },
  {
    key: 'season_steppe_khan',
    nameRu: 'Хан степи',
    nameKk: 'Дала ханы',
    nameEn: 'Steppe Khan',
    descRu: 'Закончите сезон с рангом «Хан степи»',
    descKk: 'Сезонды «Дала ханы» дәрежесімен аяқтаңыз',
    descEn: 'Finish a season with the rank Steppe Khan',
    reward: { shanyrak: 10000 },
    maxProgress: 1,
    category: 'season',
    icon: '🏹',
  },
  {
    key: 'season_golden_horde',
    nameRu: 'Воин золотой орды',
    nameKk: 'Алтын Орда жауынгері',
    nameEn: 'Golden Horde Warrior',
    descRu: 'Закончите сезон с рангом «Воин золотой орды»',
    descKk: 'Сезонды «Алтын Орда жауынгері» дәрежесімен аяқтаңыз',
    descEn: 'Finish a season with the rank Golden Horde Warrior',
    reward: { shanyrak: 25000 },
    maxProgress: 1,
    category: 'season',
    icon: '⚔️',
  },
  {
    key: 'season_great_khan',
    nameRu: 'Великий хан',
    nameKk: 'Ұлы хан',
    nameEn: 'Great Khan',
    descRu: 'Закончите сезон с рангом «Великий хан»',
    descKk: 'Сезонды «Ұлы хан» дәрежесімен аяқтаңыз',
    descEn: 'Finish a season with the rank Great Khan',
    reward: { shanyrak: 50000 },
    maxProgress: 1,
    category: 'season',
    icon: '👑',
  },

  // ============================================================
  // BOT GAME achievements (25-28)
  // ============================================================
  {
    key: 'bot_lover',
    nameRu: 'Любитель ботов',
    nameKk: 'Бот сүйіспеншісі',
    nameEn: 'Bot Lover',
    descRu: 'Сыграйте 10 игр с ботами',
    descKk: 'Боттармен 10 ойын ойнаңыз',
    descEn: 'Play 10 games with bots',
    reward: { shanyrak: 1000 },
    maxProgress: 10,
    category: 'grind',
    icon: '🤖',
  },
  {
    key: 'bot_terror',
    nameRu: 'Гроза ботов',
    nameKk: 'Боттар қорқынышы',
    nameEn: 'Bot Terror',
    descRu: 'Сыграйте 25 игр с ботами',
    descKk: 'Боттармен 25 ойын ойнаңыз',
    descEn: 'Play 25 games with bots',
    reward: { shanyrak: 3000 },
    maxProgress: 25,
    category: 'grind',
    icon: '💻',
  },
  {
    key: 'programmer',
    nameRu: 'Программист',
    nameKk: 'Бағдарламашы',
    nameEn: 'Programmer',
    descRu: 'Сыграйте 50 игр с ботами',
    descKk: 'Боттармен 50 ойын ойнаңыз',
    descEn: 'Play 50 games with bots',
    reward: { shanyrak: 5000 },
    maxProgress: 50,
    category: 'grind',
    icon: '👨‍💻',
  },
  {
    key: 'bot_hater',
    nameRu: 'Ботоненавистник',
    nameKk: 'Бот жек көруші',
    nameEn: 'Bot Hater',
    descRu: 'Сыграйте 100 игр с ботами',
    descKk: 'Боттармен 100 ойын ойнаңыз',
    descEn: 'Play 100 games with bots',
    reward: { shanyrak: 10000 },
    maxProgress: 100,
    category: 'grind',
    icon: '🔧',
  },

  // ============================================================
  // LEADERBOARD achievements (29-31)
  // ============================================================
  {
    key: 'leaderboard_1',
    nameRu: '№1',
    nameKk: '№1',
    nameEn: '#1',
    descRu: 'Займите первое место в несезонном рейтинге',
    descKk: 'Маусымдық емес рейтингте бірінші орынды алыңыз',
    descEn: 'Reach first place in the non-seasonal leaderboard',
    reward: { shanyrak: 100000, tenge: 50 },
    maxProgress: 1,
    category: 'special',
    icon: '🥇',
  },
  {
    key: 'leaderboard_2',
    nameRu: '№2',
    nameKk: '№2',
    nameEn: '#2',
    descRu: 'Займите второе место в несезонном рейтинге',
    descKk: 'Маусымдық емес рейтингте екінші орынды алыңыз',
    descEn: 'Reach second place in the non-seasonal leaderboard',
    reward: { shanyrak: 70000, tenge: 30 },
    maxProgress: 1,
    category: 'special',
    icon: '🥈',
  },
  {
    key: 'leaderboard_3',
    nameRu: '№3',
    nameKk: '№3',
    nameEn: '#3',
    descRu: 'Займите третье место в несезонном рейтинге',
    descKk: 'Маусымдық емес рейтингте үшінші орынды алыңыз',
    descEn: 'Reach third place in the non-seasonal leaderboard',
    reward: { shanyrak: 50000, tenge: 20 },
    maxProgress: 1,
    category: 'special',
    icon: '🥉',
  },

  // ============================================================
  // TUTORIAL achievements (32-34)
  // ============================================================
  {
    key: 'tutorial_student',
    nameRu: 'Ученик',
    nameKk: 'Оқушы',
    nameEn: 'Student',
    descRu: 'Пройдите обучение',
    descKk: 'Оқытудан өтіңіз',
    descEn: 'Complete the tutorial',
    reward: { shanyrak: 2000 },
    maxProgress: 1,
    category: 'beginner',
    icon: '📖',
  },
  {
    key: 'tutorial_honor',
    nameRu: 'Отличник',
    nameKk: 'Үздік оқушы',
    nameEn: 'Honor Student',
    descRu: 'Пройдите обучение дважды',
    descKk: 'Оқытудан екі рет өтіңіз',
    descEn: 'Complete the tutorial twice',
    reward: { shanyrak: 5000 },
    maxProgress: 2,
    category: 'beginner',
    icon: '📝',
  },
  {
    key: 'tutorial_grind',
    nameRu: 'Зубрила',
    nameKk: 'Жаттаушы',
    nameEn: 'Grinder',
    descRu: 'Пройдите обучение 5 раз',
    descKk: 'Оқытудан 5 рет өтіңіз',
    descEn: 'Complete the tutorial 5 times',
    reward: { shanyrak: 10000 },
    maxProgress: 5,
    category: 'beginner',
    icon: '🎓',
  },
];

export const ACHIEVEMENT_MAP: Record<string, AchievementDef> = Object.fromEntries(
  ACHIEVEMENTS.map(a => [a.key, a])
);

/** Bot ratio threshold — achievements only count if bots < this fraction */
export const MAX_BOT_RATIO = 1 / 3; // 33.4%
