/**
 * Daily Quest definitions for Казахский Дурак Онлайн.
 *
 * Rules:
 * - Each day at 00:00 Moscow time (UTC+3), 4 random quests are assigned to each player.
 * - Progress resets daily.
 * - "Король Степи" (king_of_steppe) is a meta-quest: complete 3 other daily quests.
 */

export interface DailyQuestDef {
  key: string;
  nameRu: string;
  nameKk: string;
  nameEn: string;
  nameUk: string;
  nameKa: string;
  nameAz: string;
  nameUz?: string;
  descRu: string;
  descKk: string;
  descEn: string;
  descUk: string;
  descKa: string;
  descAz: string;
  descUz?: string;
  reward: { shanyrak: number };
  /** Target value to complete the quest */
  target: number;
  /** What stat/event to track */
  trackType: DailyQuestTrackType;
  /** Whether this quest is a meta-quest (counts other completed quests) */
  isMeta?: boolean;
}

export type DailyQuestTrackType =
  | 'games_played'
  | 'games_won'
  | 'game_finished_under_15min'
  | 'cards_taken_in_game'         // took cards from table in one game ≥ target times
  | 'trump_defenses_streak_games' // defended with trump in N consecutive games
  | 'defenses_total'              // total defenses in a day
  | 'cards_thrown_total'          // total cards thrown to others in a day
  | 'rating_gained'               // rating points gained today
  | 'first_place_today'           // 1st place finishes today
  | 'shanyrak_won_today'          // shanyrak won in games today
  | 'became_durak'                // became the fool (last player) once
  | 'perfect_defense_games'       // games where defended all attacks without taking cards
  | 'trump_defenses_total'        // total trump defenses today
  | 'win_when_opponent_has_1card' // won when opponent had 1 card
  | 'spade_king_beats_trump_ace'  // beat trump ace with king of spades
  | 'spade_king_beats_trump_ace_3'// beat trump ace with king of spades 3 times
  | 'king_beats_trump_total'      // beat any trump card with king of spades N times
  | 'trump_ace_used_total'        // used trump ace N times
  | 'attack_transfers_total'      // transferred attack N times today
  | 'trump_beats_in_one_game'     // beat N cards with trump in one game
  | 'wins_in_a_row'               // N consecutive wins
  | 'cards_thrown_in_one_turn'    // threw N cards in one turn
  | 'wins_today'                  // total wins today
  | 'attacks_total'               // total attacks today
  | 'trump_ace_in_one_game'       // used trump ace N times in one game
  | 'pass_card_shown'             // showed "проездной" (pass card) N times
  | 'started_turn_with_10'        // started a turn with a 10 card N times
  | 'defended_with_777'           // defended with 777 card N times
  | 'threw_6_to_non_neighbor'     // threw a 6 to a non-neighbor player
  | 'beat_same_rank_suit_15'      // beat a card with same rank and suit 15 times
  | 'meta_quests_completed'       // completed N other daily quests today
  | 'became_durak_count'          // became durak N times
  | 'friend_added';                // added a friend (accepted friend request)

export const DAILY_QUESTS: DailyQuestDef[] = [
  // ── 1 ─────────────────────────────────────────────────────────────────────
  {
    key: 'steppe_start',
    nameRu: 'Степной старт',
    nameKk: 'Дала старты',
    nameEn: 'Steppe Start',
    nameUk: 'Степовий старт',
    nameKa: 'სტეპის დასაწყისი',
    nameAz: 'Çöl başlanğıcı',
    nameUz: 'Dasht Boshlanishi',
    descRu: 'Сыграй 5 партий',
    descKk: '5 ойын ойна',
    descEn: 'Play 5 games',
    descUk: 'Зіграй 5 партій',
    descKa: 'ითამაშე 1 თამაში',
    descAz: 'Bu gün 1 oyun oyna',
    descUz: 'Bitta oʻyin oʻynang',
    reward: { shanyrak: 150 },
    target: 5,
    trackType: 'games_played',
  },
  // ── 2 ─────────────────────────────────────────────────────────────────────
  {
    key: 'first_koshkar',
    nameRu: 'Первый Кошкар',
    nameKk: 'Алғашқы Қошқар',
    nameEn: 'First Koshkar',
    nameUk: 'Перший Кошкар',
    nameKa: 'პირველი კოშქარი',
    nameAz: 'İlk Qoşqar',
    nameUz: 'Birinchi Qoʻchqor',
    descRu: 'Выиграй 3 партии',
    descKk: '3 ойын жеңіп шық',
    descEn: 'Win 3 games',
    descUk: 'Виграй 3 партії',
    descKa: 'მოიგე 1 თამაში',
    descAz: 'Bu gün 1 oyun qazan',
    descUz: 'Birinchi marta 2-chi oʻrinda tugatish',
    reward: { shanyrak: 300 },
    target: 3,
    trackType: 'games_won',
  },
  // ── 3 ─────────────────────────────────────────────────────────────────────
  {
    key: 'bratishka',
    nameRu: 'Братишка',
    nameKk: 'Бауырым',
    nameEn: 'Bro',
    nameUk: 'Братику',
    nameKa: 'ძმა',
    nameAz: 'Qardaş',
    nameUz: 'Birodar',
    descRu: 'Добавь 1 человека в друзья',
    descKk: '1 адамды досқа қос',
    descEn: 'Add 1 person as a friend',
    descUk: 'Додай 1 людину в друзі',
    descKa: 'ითამაშე 3 თამაში',
    descAz: 'Bu gün 2 oyun qazan',
    descUz: 'Doʻstingiz bilan oʻyin oʻynang',
    reward: { shanyrak: 300 },
    target: 1,
    trackType: 'friend_added',
  },
  // ── 4 ─────────────────────────────────────────────────────────────────────
  {
    key: 'altyn_novice',
    nameRu: 'Алтын новичок',
    nameKk: 'Алтын жаңадан',
    nameEn: 'Golden Novice',
    nameUk: 'Золотий новачок',
    nameKa: 'ოქროს ნოვიცი',
    nameAz: 'Qızıl yeni başlayan',
    nameUz: 'Oltin Yangi Boshlovchi',
    descRu: 'Сыграй 8 партий',
    descKk: '8 ойын ойна',
    descEn: 'Play 8 games',
    descUk: 'Зіграй 8 партій',
    descKa: 'დააგროვე 10 რეიტინგის ქულა',
    descAz: 'Bu gün 3 oyun oyna',
    descUz: '50 tenge yigʻing',
    reward: { shanyrak: 300 },
    target: 8,
    trackType: 'games_played',
  },
  // ── 5 ─────────────────────────────────────────────────────────────────────
  {
    key: 'rabbit_in_steppe',
    nameRu: 'Заяц в степи',
    nameKk: 'Даладағы қоян',
    nameEn: 'Rabbit in the Steppe',
    nameUk: 'Заєць у степу',
    nameKa: 'კურდღელი სტეპში',
    nameAz: 'Çöldə dovşan',
    nameUz: 'Dashtdagi Quyon',
    descRu: 'Возьми карты, если не можешь побиться, 3 раза за партию',
    descKk: 'Бір ойында жауап бере алмай 3 рет карта ал',
    descEn: 'Pick up cards when unable to defend, 3 times in one game',
    descUk: 'Візьми карти, якщо не можеш відбитися, 3 рази за партію',
    descKa: 'ბოლოდან მეორე ადგილი დაიკავე 1 თამაშში',
    descAz: '15 dəqiqədən az müddətdə oyunu bitir',
    descUz: 'Birinchi oʻyiningizda yutqazing',
    reward: { shanyrak: 200 },
    target: 3,
    trackType: 'cards_taken_in_game',
  },
  // ── 6 ─────────────────────────────────────────────────────────────────────
  {
    key: 'first_trump_streak',
    nameRu: 'Первый козырь',
    nameKk: 'Алғашқы козырь',
    nameEn: 'First Trump',
    nameUk: 'Перший козир',
    nameKa: 'პირველი კოზირი',
    nameAz: 'İlk koz seriyası',
    nameUz: 'Birinchi Koz',
    descRu: 'Побейся козырем в 10 партиях подряд',
    descKk: '10 ойын қатарынан козырьмен жауап бер',
    descEn: 'Defend with a trump card in 10 consecutive games',
    descUk: 'Відбийся козирем у 10 партіях поспіль',
    descKa: 'ზედიზედ 3 თამაშში კოზირით დაიცვი',
    descAz: '3 ardıcıl oyunda koz ilə müdafiə et',
    descUz: 'Birinchi marta koz bilan urish',
    reward: { shanyrak: 200 },
    target: 10,
    trackType: 'trump_defenses_streak_games',
  },
  // ── 7 ─────────────────────────────────────────────────────────────────────
  {
    key: 'steppe_warrior_daily',
    nameRu: 'Степной воин',
    nameKk: 'Дала жауынгері',
    nameEn: 'Steppe Warrior',
    nameUk: 'Степовий воїн',
    nameKa: 'სტეპის მებრძოლი',
    nameAz: 'Çöl döyüşçüsü',
    nameUz: 'Dasht Jangchisi',
    descRu: 'Сыграй 10 партий',
    descKk: '10 ойын ойна',
    descEn: 'Play 10 games',
    descUk: 'Зіграй 10 партій',
    descKa: 'ითამაშე 5 თამაში',
    descAz: 'Bu gün 5 oyun oyna',
    descUz: '3 ta oʻyin oʻynang',
    reward: { shanyrak: 400 },
    target: 10,
    trackType: 'games_played',
  },
  // ── 8 ─────────────────────────────────────────────────────────────────────
  {
    key: 'little_batyr',
    nameRu: 'Маленький батыр',
    nameKk: 'Кішкентай батыр',
    nameEn: 'Little Batyr',
    nameUk: 'Маленький батир',
    nameKa: 'პატარა ბატირი',
    nameAz: 'Kiçik Batır',
    nameUz: 'Kichik Batyr',
    descRu: 'Отбей 15 атак',
    descKk: '15 шабуылды тойтар',
    descEn: 'Deflect 15 attacks',
    descUk: 'Відбий 15 атак',
    descKa: 'ერთ თამაშში 5 თავდასხმა დაიცვი',
    descAz: 'Bu gün 3 oyun qazan',
    descUz: 'Bitta oʻyinda gʻalaba qozonish',
    reward: { shanyrak: 200 },
    target: 15,
    trackType: 'defenses_total',
  },
  // ── 9 ─────────────────────────────────────────────────────────────────────
  {
    key: 'quick_start_daily',
    nameRu: 'Быстрый старт',
    nameKk: 'Жылдам старт',
    nameEn: 'Quick Start',
    nameUk: 'Швидкий старт',
    nameKa: 'სწრაფი დასაწყისი',
    nameAz: 'Sürətli başlanğıc',
    nameUz: 'Tezkor Boshlanish',
    descRu: 'Выиграй 4 партии за день',
    descKk: 'Күн ішінде 4 ойын жеңіп шық',
    descEn: 'Win 4 games today',
    descUk: 'Виграй 4 партії за день',
    descKa: 'მოიგე 3 თამაში',
    descAz: 'Bu gün 2 oyun 15 dəqiqədən az müddətdə bitir',
    descUz: '5 daqiqadan kam vaqtda gʻalaba qozonish',
    reward: { shanyrak: 250 },
    target: 4,
    trackType: 'wins_today',
  },
  // ── 10 ────────────────────────────────────────────────────────────────────
  {
    key: 'tulpar_warmup',
    nameRu: 'Тулпар-разминка',
    nameKk: 'Тұлпар жаттығуы',
    nameEn: 'Tulpar Warmup',
    nameUk: 'Тулпар-розминка',
    nameKa: 'ტულპარის გათბობა',
    nameAz: 'Tulpar istiləşməsi',
    nameUz: 'Tulpar Isitish',
    descRu: 'Отбейся 10 раз',
    descKk: '10 рет жауап бер',
    descEn: 'Defend 10 times',
    descUk: 'Відбийся 10 разів',
    descKa: 'ითამაშე 2 თამაში 15 წუთში',
    descAz: 'Bu gün 20 müdafiə et',
    descUz: '2 ta oʻyin oʻynang',
    reward: { shanyrak: 150 },
    target: 10,
    trackType: 'defenses_total',
  },
  // ── 11 ────────────────────────────────────────────────────────────────────
  {
    key: 'koshkar_woke_up',
    nameRu: 'Кошкар проснулся',
    nameKk: 'Қошқар оянды',
    nameEn: 'Koshkar Woke Up',
    nameUk: 'Кошкар прокинувся',
    nameKa: 'კოშქარი გაიღვიძა',
    nameAz: 'Qoşqar oyandı',
    nameUz: 'Qoʻchqor Uygʻondi',
    descRu: 'Подкинь 30 карт другим игрокам за день',
    descKk: 'Күн ішінде басқа ойыншыларға 30 карта лақтыр',
    descEn: 'Throw 30 cards to other players today',
    descUk: 'Підкинь 30 карт іншим гравцям за день',
    descKa: 'ბარათები 10-ჯერ ხელიდან ჩამოაგდე',
    descAz: 'Bu gün 5 oyun qazan',
    descUz: 'Ertalab 8:00 dan oldin oʻyin oʻynang',
    reward: { shanyrak: 200 },
    target: 30,
    trackType: 'cards_thrown_total',
  },
  // ── 12 ────────────────────────────────────────────────────────────────────
  {
    key: 'golden_debut',
    nameRu: 'Золотой дебют',
    nameKk: 'Алтын дебют',
    nameEn: 'Golden Debut',
    nameUk: 'Золотий дебют',
    nameKa: 'ოქროს დებიუტი',
    nameAz: 'Qızıl debüt',
    nameUz: 'Oltin Debut',
    descRu: 'Набери 100 очков рейтинга за все партии',
    descKk: 'Барлық ойындарда 100 рейтинг ұпайын жина',
    descEn: 'Gain 100 rating points across all games',
    descUk: 'Набери 100 очок рейтингу за всі партії',
    descKa: 'დააგროვე 20 რეიტინგის ქულა',
    descAz: 'Bu gün 100 reytinq xalı qazan',
    descUz: 'Birinchi oʻyiningizda gʻalaba qozonish',
    reward: { shanyrak: 200 },
    target: 100,
    trackType: 'rating_gained',
  },
  // ── 13 ────────────────────────────────────────────────────────────────────
  {
    key: 'steppe_student_daily',
    nameRu: 'Степной ученик',
    nameKk: 'Дала шәкірті',
    nameEn: 'Steppe Student',
    nameUk: 'Степовий учень',
    nameKa: 'სტეპის მოსწავლე',
    nameAz: 'Çöl tələbəsi',
    nameUz: 'Dasht Talabasi',
    descRu: 'Сыграй 12 партий',
    descKk: '12 ойын ойна',
    descEn: 'Play 12 games',
    descUk: 'Зіграй 12 партій',
    descKa: 'ითამაშე 7 თამაში',
    descAz: 'Bu gün 10 oyun oyna',
    descUz: '5 ta oʻyin oʻynang',
    reward: { shanyrak: 750 },
    target: 12,
    trackType: 'games_played',
  },
  // ── 14 ────────────────────────────────────────────────────────────────────
  {
    key: 'first_berkut_daily',
    nameRu: 'Первый беркут',
    nameKk: 'Алғашқы бүркіт',
    nameEn: 'First Berkut',
    nameUk: 'Перший беркут',
    nameKa: 'პირველი ბერკუტი',
    nameAz: 'İlk Berkut',
    nameUz: 'Birinchi Berkut',
    descRu: 'Займи 1-е место в трёх матчах за день',
    descKk: 'Күн ішінде үш матчта 1-ші орынды ал',
    descEn: 'Finish 1st in three matches today',
    descUk: 'Займи 1-е місце у трьох матчах за день',
    descKa: 'დაასრულე 1 თამაში ხელში 1 ბარათით',
    descAz: 'Bu gün 1-ci yeri al',
    descUz: 'Birinchi marta berkut nishonini oling',
    reward: { shanyrak: 400 },
    target: 3,
    trackType: 'first_place_today',
  },
  // ── 15 ────────────────────────────────────────────────────────────────────
  {
    key: 'khan_day',
    nameRu: 'Ханский день',
    nameKk: 'Хандық күн',
    nameEn: "Khan's Day",
    nameUk: 'Ханський день',
    nameKa: 'ხანის დღე',
    nameAz: 'Xan günü',
    nameUz: 'Xon Kuni',
    descRu: 'Выиграй 1000 шаныраков в играх с другими игроками',
    descKk: 'Басқа ойыншылармен ойындарда 1000 шаңырақ ұтып ал',
    descEn: 'Win 1000 shanyrak in games with other players',
    descUk: 'Виграй 1000 шаніраків в іграх з іншими гравцями',
    descKa: 'მოიგე 5 თამაში',
    descAz: 'Bu gün 3 dəfə 1-ci yeri al',
    descUz: 'Bir kunda 3 ta gʻalaba qozonish',
    reward: { shanyrak: 300 },
    target: 1000,
    trackType: 'shanyrak_won_today',
  },
  // ── 16 ────────────────────────────────────────────────────────────────────
  {
    key: 'really_sure',
    nameRu: 'А точно ли?',
    nameKk: 'Шынымен бе?',
    nameEn: 'Are You Sure?',
    nameUk: 'А точно?',
    nameKa: 'დარწმუნებული ხარ?',
    nameAz: 'Əminsiniz?',
    nameUz: 'Haqiqatan Ishonchli',
    descRu: 'Стань дураком 1 раз',
    descKk: '1 рет ақымақ бол',
    descEn: 'Become the fool once',
    descUk: 'Стань дурнем 1 раз',
    descKa: 'გახდი სულელი (ბოლო მოთამაშე) 1-ჯერ',
    descAz: 'Bir oyunda 10+ kart götür',
    descUz: 'Bir oʻyinda 5 ta karta tashlash',
    reward: { shanyrak: 100 },
    target: 1,
    trackType: 'became_durak',
  },
  // ── 17 ────────────────────────────────────────────────────────────────────
  {
    key: 'throw_king',
    nameRu: 'Король подкидывания',
    nameKk: 'Лақтырудың королі',
    nameEn: 'Throw King',
    nameUk: 'Король підкидання',
    nameKa: 'გადაყარე მეფე',
    nameAz: 'Padşah at',
    nameUz: 'Tashlash Qiroli',
    descRu: 'Подкинь 50 карт другим игрокам за день',
    descKk: 'Күн ішінде басқа ойыншыларға 50 карта лақтыр',
    descEn: 'Throw 50 cards to other players today',
    descUk: 'Підкинь 50 карт іншим гравцям за день',
    descKa: 'სხვებს 20 ბარათი გადაუდე',
    descAz: 'Bu gün 10 kart at',
    descUz: 'Bir oʻyinda 10 ta karta tashlash',
    reward: { shanyrak: 300 },
    target: 50,
    trackType: 'cards_thrown_total',
  },
  // ── 18 ────────────────────────────────────────────────────────────────────
  {
    key: 'perfect_defense_daily',
    nameRu: 'Идеальная защита',
    nameKk: 'Мінсіз қорғаныс',
    nameEn: 'Perfect Defense',
    nameUk: 'Ідеальний захист',
    nameKa: 'სრულყოფილი დაცვა',
    nameAz: 'Mükəmməl müdafiə',
    nameUz: 'Mukammal Mudofaa',
    descRu: 'Отбей все атаки в 1 партии, ни разу не взяв карты со стола себе в руку',
    descKk: 'Бір ойында барлық шабуылды тойтар, столдан бірде-бір карта алмай',
    descEn: 'Deflect all attacks in 1 game without picking up any cards',
    descUk: 'Відбий всі атаки в 1 партії, жодного разу не взявши карти зі столу',
    descKa: '2 თამაში ყველა თავდასხმა დაიცვი ბარათების არ აღებით',
    descAz: 'Kart götürmədən 2 oyun bitir',
    descUz: 'Hech qanday karta olmay gʻalaba qozonish',
    reward: { shanyrak: 400 },
    target: 1,
    trackType: 'perfect_defense_games',
  },
  // ── 19 ────────────────────────────────────────────────────────────────────
  {
    key: 'trump_rain',
    nameRu: 'Козырной дождь',
    nameKk: 'Козырь жаңбыры',
    nameEn: 'Trump Rain',
    nameUk: 'Козирний дощ',
    nameKa: 'კოზირის წვიმა',
    nameAz: 'Koz yağışı',
    nameUz: 'Koz Yomgʻiri',
    descRu: 'Отбейся козырем 20 раз за одну партию',
    descKk: 'Бір ойында козырьмен 20 рет жауап бер',
    descEn: 'Defend with a trump card 20 times in one game',
    descUk: 'Відбийся козирем 20 разів за одну партію',
    descKa: 'კოზირით 10 ბარათი გაარიე',
    descAz: 'Bu gün 10 koz müdafiəsi et',
    descUz: 'Bir oʻyinda 5 ta koz bilan urish',
    reward: { shanyrak: 200 },
    target: 20,
    trackType: 'trump_beats_in_one_game',
  },
  // ── 20 ────────────────────────────────────────────────────────────────────
  {
    key: 'iron_defense',
    nameRu: 'Железная оборона',
    nameKk: 'Темір қорғаныс',
    nameEn: 'Iron Defense',
    nameUk: 'Залізна оборона',
    nameKa: 'რკინის დაცვა',
    nameAz: 'Dəmir müdafiə',
    nameUz: 'Temir Mudofaa',
    descRu: 'Отбей все атаки в 3-х партиях, ни разу не взяв карты со стола себе в руку',
    descKk: '3 ойында барлық шабуылды тойтар, столдан бірде-бір карта алмай',
    descEn: 'Deflect all attacks in 3 games without picking up any cards',
    descUk: 'Відбий всі атаки в 3 партіях, жодного разу не взявши карти зі столу',
    descKa: 'ჯამში 30 თავდასხმა დაიცვი',
    descAz: 'Bu gün 30 müdafiə et',
    descUz: 'Ketma-ket 3 ta hujumni qaytarish',
    reward: { shanyrak: 700 },
    target: 3,
    trackType: 'perfect_defense_games',
  },
  // ── 21 ────────────────────────────────────────────────────────────────────
  {
    key: 'last_hero',
    nameRu: 'Последний герой',
    nameKk: 'Соңғы батыр',
    nameEn: 'Last Hero',
    nameUk: 'Останній герой',
    nameKa: 'ბოლო გმირი',
    nameAz: 'Son qəhrəman',
    nameUz: 'Oxirgi Qahramon',
    descRu: 'Выиграй партию, когда у противника осталась 1 карта',
    descKk: 'Қарсыласыңда 1 карта қалғанда ойынды жеңіп шық',
    descEn: 'Win a game when your opponent has only 1 card left',
    descUk: 'Виграй партію, коли у суперника залишилась 1 карта',
    descKa: 'ბოლოდან მეორე ადგილი 2-ჯერ დაიკავე',
    descAz: 'Axmaq ol (son oyunçu)',
    descUz: 'Oxirgi karta bilan gʻalaba qozonish',
    reward: { shanyrak: 300 },
    target: 1,
    trackType: 'win_when_opponent_has_1card',
  },
  // ── 22 ────────────────────────────────────────────────────────────────────
  {
    key: 'invincible_ace_spades',
    nameRu: 'Непобедимый Туз пики',
    nameKk: 'Жеңілмес пика тузы',
    nameEn: 'Invincible Ace of Spades',
    nameUk: 'Непереможний Туз пік',
    nameKa: 'სპადების ტუზი',
    nameAz: 'Yenilməz Maça Tuzu',
    nameUz: 'Yengilmas Pik Tuz',
    descRu: 'Побей короля пики тузом пики 5 раз',
    descKk: 'Пика королін пика тузымен 5 рет жеңіп шық',
    descEn: 'Beat the King of Spades with the Ace of Spades 5 times',
    descUk: 'Побий короля пік тузом пік 5 разів',
    descKa: 'სპადების ტუზით კოზირის ტუზი გაარიე',
    descAz: 'Maça Padşahı ilə koz tuzunu döy',
    descUz: 'Pik tuz bilan 3 ta karta urish',
    reward: { shanyrak: 300 },
    target: 5,
    trackType: 'spade_king_beats_trump_ace',
  },
  // ── 23 ────────────────────────────────────────────────────────────────────
  {
    key: 'ace_spades_master',
    nameRu: 'Мастер Туза пик',
    nameKk: 'Пика тузының шебері',
    nameEn: 'Ace of Spades Master',
    nameUk: 'Майстер Туза пік',
    nameKa: 'სპადების ტუზის ოსტატი',
    nameAz: 'Maça Tuzu ustası',
    nameUz: 'Pik Tuz Ustasi',
    descRu: 'Побей короля пики тузом пики 3 раза',
    descKk: 'Пика королін пика тузымен 3 рет жеңіп шық',
    descEn: 'Beat the King of Spades with the Ace of Spades 3 times',
    descUk: 'Побий короля пік тузом пік 3 рази',
    descKa: 'სპადების ტუზით კოზირის ტუზი 3-ჯერ გაარიე',
    descAz: 'Maça Padşahı ilə koz tuzunu 3 dəfə döy',
    descUz: 'Bir oʻyinda pik tuz bilan 5 ta karta urish',
    reward: { shanyrak: 150 },
    target: 3,
    trackType: 'spade_king_beats_trump_ace_3',
  },
  // ── 24 ────────────────────────────────────────────────────────────────────
  {
    key: 'spade_king_daily',
    nameRu: 'Король пики',
    nameKk: 'Пика королі',
    nameEn: 'King of Spades',
    nameUk: 'Король пік',
    nameKa: 'სპადების მეფე',
    nameAz: 'Günlük Maça Padşahı',
    nameUz: 'Pik Qiroli',
    descRu: 'Побей любую козырную карту королём пики 5 раз',
    descKk: 'Кез келген козырь картаны пика королімен 5 рет жеңіп шық',
    descEn: 'Beat any trump card with the King of Spades 5 times',
    descUk: 'Побий будь-яку козирну карту королем пік 5 разів',
    descKa: 'სპადების მეფით ბარათები 5-ჯერ გაარიე',
    descAz: 'Maça Padşahı ilə koz kartını döy',
    descUz: 'Qirgʻich bilan 5 ta karta urish',
    reward: { shanyrak: 300 },
    target: 5,
    trackType: 'king_beats_trump_total',
  },
  // ── 25 ────────────────────────────────────────────────────────────────────
  {
    key: 'king_of_kings',
    nameRu: 'Король всех королей',
    nameKk: 'Барлық корольдердің королі',
    nameEn: 'King of All Kings',
    nameUk: 'Король усіх королів',
    nameKa: 'მეფეთა მეფე',
    nameAz: 'Padşahların padşahı',
    nameUz: 'Qirollar Qiroli',
    descRu: 'Побей любую козырную карту королём пики 10 раз',
    descKk: 'Кез келген козырь картаны пика королімен 10 рет жеңіп шық',
    descEn: 'Beat any trump card with the King of Spades 10 times',
    descUk: 'Побий будь-яку козирну карту королем пік 10 разів',
    descKa: 'სპადების მეფით ბარათები 10-ჯერ გაარიე',
    descAz: 'Maça Padşahı ilə 5 koz kartı döy',
    descUz: 'Bir oʻyinda barcha qirollarni ishlatish',
    reward: { shanyrak: 700 },
    target: 10,
    trackType: 'king_beats_trump_total',
  },
  // ── 26 ────────────────────────────────────────────────────────────────────
  {
    key: 'trump_ace_master',
    nameRu: 'Козырной мастер',
    nameKk: 'Козырь шебері',
    nameEn: 'Trump Master',
    nameUk: 'Козирний майстер',
    nameKa: 'კოზირის ოსტატი',
    nameAz: 'Koz Tuzu ustası',
    nameUz: 'Koz Tuz Ustasi',
    descRu: 'Используй козырного туза 6 раз',
    descKk: 'Козырь тузын 6 рет қолдан',
    descEn: 'Use the trump ace 6 times',
    descUk: 'Використай козирного туза 6 разів',
    descKa: 'კოზირის ტუზი 5-ჯერ გამოიყენე',
    descAz: 'Koz Tuzunu 5 dəfə istifadə et',
    descUz: 'Koz tuz bilan 3 ta karta urish',
    reward: { shanyrak: 300 },
    target: 6,
    trackType: 'trump_ace_used_total',
  },
  // ── 27 ────────────────────────────────────────────────────────────────────
  {
    key: 'king_of_steppe',
    nameRu: 'Король Степи',
    nameKk: 'Дала Королі',
    nameEn: 'King of the Steppe',
    nameUk: 'Король Степу',
    nameKa: 'სტეპის მეფე',
    nameAz: 'Çölün padşahı',
    nameUz: 'Dasht Qiroli',
    descRu: 'Выполни 3 любых ежедневных задания за день',
    descKk: 'Күн ішінде кез келген 3 күнделікті тапсырманы орында',
    descEn: 'Complete any 3 daily quests today',
    descUk: 'Виконай 3 будь-яких щоденних завдання за день',
    descKa: 'დღეს 3 სხვა ყოველდღიური დავალება შეასრულე',
    descAz: 'Bu gün 3 gündəlik tapşırıq tamamla',
    descUz: 'Bir kunda 5 ta gʻalaba qozonish',
    reward: { shanyrak: 500 },
    target: 3,
    trackType: 'meta_quests_completed',
    isMeta: true,
  },
  // ── 28 ────────────────────────────────────────────────────────────────────
  {
    key: 'first_transfer',
    nameRu: 'Первый перевод',
    nameKk: 'Алғашқы аудару',
    nameEn: 'First Transfer',
    nameUk: 'Перший переклад',
    nameKa: 'პირველი გადაცემა',
    nameAz: 'İlk ötürmə',
    nameUz: 'Birinchi Oʻtkazish',
    descRu: 'Переведи атаку 5 раз за день',
    descKk: 'Күн ішінде шабуылды 5 рет аудар',
    descEn: 'Transfer the attack 5 times today',
    descUk: 'Переведи атаку 5 разів за день',
    descKa: 'თავდასხმა 5-ჯერ გადააციე',
    descAz: 'Hücumu 1 dəfə ötür',
    descUz: 'Birinchi marta karta oʻtkazish',
    reward: { shanyrak: 150 },
    target: 5,
    trackType: 'attack_transfers_total',
  },
  // ── 29 ────────────────────────────────────────────────────────────────────
  {
    key: 'transfer_master',
    nameRu: 'Мастер перевода',
    nameKk: 'Аудару шебері',
    nameEn: 'Transfer Master',
    nameUk: 'Майстер переводу',
    nameKa: 'გადაცემის ოსტატი',
    nameAz: 'Ötürmə ustası',
    nameUz: 'Oʻtkazish Ustasi',
    descRu: 'Переведи атаку 15 раз за день',
    descKk: 'Күн ішінде шабуылды 15 рет аудар',
    descEn: 'Transfer the attack 15 times today',
    descUk: 'Переведи атаку 15 разів за день',
    descKa: 'თავდასხმა 15-ჯერ გადააციე',
    descAz: 'Bu gün hücumu 5 dəfə ötür',
    descUz: 'Bir oʻyinda 3 ta karta oʻtkazish',
    reward: { shanyrak: 250 },
    target: 15,
    trackType: 'attack_transfers_total',
  },
  // ── 30 ────────────────────────────────────────────────────────────────────
  {
    key: 'trump_hunter',
    nameRu: 'Козырной охотник',
    nameKk: 'Козырь аңшысы',
    nameEn: 'Trump Hunter',
    nameUk: 'Козирний мисливець',
    nameKa: 'კოზირის მონადირე',
    nameAz: 'Koz ovçusu',
    nameUz: 'Koz Ovchisi',
    descRu: 'Побей козырем 15 карт за одну партию',
    descKk: 'Бір ойында козырьмен 15 карта жеңіп шық',
    descEn: 'Beat 15 cards with trumps in one game',
    descUk: 'Побий козирем 15 карт за одну партію',
    descKa: 'კოზირით 20 ბარათი გაარიე',
    descAz: 'Bir oyunda 5 koz kartı ilə döy',
    descUz: 'Bir oʻyinda 7 ta koz bilan urish',
    reward: { shanyrak: 200 },
    target: 15,
    trackType: 'trump_beats_in_one_game',
  },
  // ── 31 ────────────────────────────────────────────────────────────────────
  {
    key: 'serial_winner',
    nameRu: 'Серийный победитель',
    nameKk: 'Сериялы жеңімпаз',
    nameEn: 'Serial Winner',
    nameUk: 'Серійний переможець',
    nameKa: 'სერიული გამარჯვებული',
    nameAz: 'Serial qalib',
    nameUz: 'Ketma-ket Gʻolib',
    descRu: 'Выиграй 2 партии подряд',
    descKk: 'Қатарынан 2 ойын жеңіп шық',
    descEn: 'Win 2 games in a row',
    descUk: 'Виграй 2 партії поспіль',
    descKa: 'ზედიზედ 3 თამაში მოიგე',
    descAz: '3 ardıcıl oyun qazan',
    descUz: 'Ketma-ket 3 ta gʻalaba qozonish',
    reward: { shanyrak: 250 },
    target: 2,
    trackType: 'wins_in_a_row',
  },
  // ── 32 ────────────────────────────────────────────────────────────────────
  {
    key: 'card_storm',
    nameRu: 'Карточный шторм',
    nameKk: 'Карта дауылы',
    nameEn: 'Card Storm',
    nameUk: 'Картковий шторм',
    nameKa: 'ბარათების ქარიშხალი',
    nameAz: 'Kart fırtınası',
    nameUz: 'Karta Boʻroni',
    descRu: 'Подкинь 10 карт за один ход',
    descKk: 'Бір жүрісте 10 карта лақтыр',
    descEn: 'Throw 10 cards in one turn',
    descUk: 'Підкинь 10 карт за один хід',
    descKa: 'ერთ სვლაში 5 ბარათი გადაუდე',
    descAz: 'Bir növbədə 4 kart at',
    descUz: 'Bir oʻyinda 15 ta karta tashlash',
    reward: { shanyrak: 200 },
    target: 10,
    trackType: 'cards_thrown_in_one_turn',
  },
  // ── 33 ────────────────────────────────────────────────────────────────────
  {
    key: 'unstoppable',
    nameRu: 'Неудержимый',
    nameKk: 'Тоқтатылмайтын',
    nameEn: 'Unstoppable',
    nameUk: 'Невтримний',
    nameKa: 'გაუჩერებელი',
    nameAz: 'Dayandırılmaz',
    nameUz: 'Toʻxtatib Boʻlmas',
    descRu: 'Выиграй 5 партий за день',
    descKk: 'Күн ішінде 5 ойын жеңіп шық',
    descEn: 'Win 5 games today',
    descUk: 'Виграй 5 партій за день',
    descKa: 'ჯამში 10 თამაში მოიგე',
    descAz: 'Bu gün 7 oyun qazan',
    descUz: 'Ketma-ket 5 ta gʻalaba qozonish',
    reward: { shanyrak: 500 },
    target: 5,
    trackType: 'wins_today',
  },
  // ── 34 ────────────────────────────────────────────────────────────────────
  {
    key: 'bold_move',
    nameRu: 'Дерзкий ход',
    nameKk: 'Батыл жүріс',
    nameEn: 'Bold Move',
    nameUk: 'Зухвалий хід',
    nameKa: 'გამბედავი სვლა',
    nameAz: 'Cəsur hərəkət',
    nameUz: 'Jasur Harakat',
    descRu: 'Побей туза другим тузом 3 раза',
    descKk: 'Тузды басқа тузбен 3 рет жеңіп шық',
    descEn: 'Beat an ace with another ace 3 times',
    descUk: 'Побий туза іншим тузом 3 рази',
    descKa: 'ბარათები 10-ჯერ გადაუდე სხვებს',
    descAz: '1 kartı olan rəqibə qalib gəl',
    descUz: 'Bitta kartani 3 ta raqibga tashlash',
    reward: { shanyrak: 300 },
    target: 3,
    trackType: 'trump_ace_used_total',
  },
  // ── 35 ────────────────────────────────────────────────────────────────────
  {
    key: 'attack_master',
    nameRu: 'Мастер атаки',
    nameKk: 'Шабуыл шебері',
    nameEn: 'Attack Master',
    nameUk: 'Майстер атаки',
    nameKa: 'თავდასხმის ოსტატი',
    nameAz: 'Hücum ustası',
    nameUz: 'Hujum Ustasi',
    descRu: 'Атакуй 20 раз за день',
    descKk: 'Күн ішінде 20 рет шабуыл жаса',
    descEn: 'Attack 20 times today',
    descUk: 'Атакуй 20 разів за день',
    descKa: 'ჯამში 30 თავდასხმა გაიმართე',
    descAz: 'Bu gün 30 hücum et',
    descUz: 'Bir oʻyinda 8 ta hujum qilish',
    reward: { shanyrak: 200 },
    target: 20,
    trackType: 'attacks_total',
  },
  // ── 36 ────────────────────────────────────────────────────────────────────
  {
    key: 'trump_ace_game',
    nameRu: 'Козырной туз',
    nameKk: 'Козырь тузы',
    nameEn: 'Trump Ace',
    nameUk: 'Козирний туз',
    nameKa: 'კოზირის ტუზი',
    nameAz: 'Oyunda Koz Tuzu',
    nameUz: 'Koz Tuz Oʻyini',
    descRu: 'Используй козырного туза 3 раза за одну партию',
    descKk: 'Бір ойында козырь тузын 3 рет қолдан',
    descEn: 'Use the trump ace 3 times in one game',
    descUk: 'Використай козирного туза 3 рази за одну партію',
    descKa: 'ერთ თამაშში კოზირის ტუზი 3-ჯერ გამოიყენე',
    descAz: 'Bir oyunda Koz Tuzunu 3 dəfə istifadə et',
    descUz: 'Koz tuz bilan gʻalaba qozonish',
    reward: { shanyrak: 250 },
    target: 3,
    trackType: 'trump_ace_in_one_game',
  },
  // ── 37 ────────────────────────────────────────────────────────────────────
  {
    key: 'lets_go',
    nameRu: 'Давай дальше',
    nameKk: 'Жүре бер',
    nameEn: "Let's Go",
    nameUk: 'Давай далі',
    nameKa: 'წავიდეთ!',
    nameAz: 'Gedək!',
    nameUz: 'Ketdik!',
    descRu: 'Покажи проездной 5 раз',
    descKk: 'Өткізгішті 5 рет көрсет',
    descEn: 'Show the pass card 5 times',
    descUk: 'Покажи перепустку 5 разів',
    descKa: '«გამტარი» ბარათი 3-ჯერ ჩვენი',
    descAz: '"Proezdnoy" kartını göstər',
    descUz: '3 ta oʻyinda ketma-ket hujum qilish',
    reward: { shanyrak: 300 },
    target: 5,
    trackType: 'pass_card_shown',
  },
  // ── 38 ────────────────────────────────────────────────────────────────────
  {
    key: 'shall_we_ride',
    nameRu: 'Прокатимся?',
    nameKk: 'Жүрейік пе?',
    nameEn: 'Shall We Ride?',
    nameUk: 'Прокатимось?',
    nameKa: 'ვიმგზავრებთ?',
    nameAz: 'Gedəkmi?',
    nameUz: 'Uchaylikmi?',
    descRu: 'Покажи проездной 10 раз',
    descKk: 'Өткізгішті 10 рет көрсет',
    descEn: 'Show the pass card 10 times',
    descUk: 'Покажи перепустку 10 разів',
    descKa: 'სვლა 10-ით 3-ჯერ დაიწყე',
    descAz: '"Proezdnoy" kartını 3 dəfə göstər',
    descUz: 'Tulpar bilan gʻalaba qozonish',
    reward: { shanyrak: 500 },
    target: 10,
    trackType: 'pass_card_shown',
  },
  // ── 39 ────────────────────────────────────────────────────────────────────
  {
    key: 'werewolf',
    nameRu: 'Оборотень',
    nameKk: 'Айналмалы',
    nameEn: 'Werewolf',
    nameUk: 'Перевертень',
    nameKa: 'მგელი',
    nameAz: 'Qurdadam',
    nameUz: 'Boʻri',
    descRu: 'Начни ход с 10-ки 3 раза',
    descKk: '10-шымен жүрісті 3 рет баста',
    descEn: 'Start a turn with a 10 card 3 times',
    descUk: 'Почни хід з 10-ки 3 рази',
    descKa: '777 ბარათით 3-ჯერ დაიცვი',
    descAz: '777 kartı ilə müdafiə et',
    descUz: 'Bir oʻyinda 4 ta turli xil koz ishlatish',
    reward: { shanyrak: 300 },
    target: 3,
    trackType: 'started_turn_with_10',
  },
  // ── 40 ────────────────────────────────────────────────────────────────────
  {
    key: 'flipper',
    nameRu: 'Перевертыш',
    nameKk: 'Аударғыш',
    nameEn: 'Flipper',
    nameUk: 'Перевертень-майстер',
    nameKa: 'ბრუნვა',
    nameAz: 'Çevirici',
    nameUz: 'Agʻdaruvchi',
    descRu: 'Начни ход с 10-ки 5 раз',
    descKk: '10-шымен жүрісті 5 рет баста',
    descEn: 'Start a turn with a 10 card 5 times',
    descUk: 'Почни хід з 10-ки 5 разів',
    descKa: '10-ით ითამაშე და თამაშის მიმართულება შეაბრუნე',
    descAz: '10 kartı ilə növbəyə başla',
    descUz: 'Bir oʻyinda 3 ta karta agʻdarish',
    reward: { shanyrak: 500 },
    target: 5,
    trackType: 'started_turn_with_10',
  },
  // ── 41 ────────────────────────────────────────────────────────────────────
  {
    key: 'in_suit',
    nameRu: 'В масть',
    nameKk: 'Мастьке сай',
    nameEn: 'In Suit',
    nameUk: 'В масть',
    nameKa: 'ერთი ფერი',
    nameAz: 'Uyğun',
    nameUz: 'Kostyumda',
    descRu: "Отбейся картой «777» 3 раза",
    descKk: '«777» картасымен 3 рет жауап бер',
    descEn: 'Defend with the 777 card 3 times',
    descUk: 'Відбийся картою «777» 3 рази',
    descKa: 'ერთი ფერის ბარათი 15-ჯერ ერთი ფერის ბარათით გაარიე',
    descAz: 'Bir oyunda 20 müdafiə et',
    descUz: 'Bir xil mastdan 5 ta karta tashlash',
    reward: { shanyrak: 500 },
    target: 3,
    trackType: 'defended_with_777',
  },
  // ── 42 ────────────────────────────────────────────────────────────────────
  {
    key: 'foundling',
    nameRu: 'Подкидыш',
    nameKk: 'Лақтырылған',
    nameEn: 'Foundling',
    nameUk: 'Підкидень',
    nameKa: 'ნაპოვარი',
    nameAz: 'Tapıntı',
    nameUz: 'Topilgan Bola',
    descRu: 'Подкинь 6-ку игроку, когда не являешься его соседом',
    descKk: 'Көршің болмаған ойыншыға 6-шыны лақтыр',
    descEn: 'Throw a 6 to a player who is not your neighbor',
    descUk: 'Підкинь 6-ку гравцю, коли не є його сусідом',
    descKa: 'სხვა მოთამაშეს 6 გადაუდე',
    descAz: 'Bu gün 500 şanyrak qazan',
    descUz: 'Boshqa oʻyinchi tashlab ketgan kartani olish',
    reward: { shanyrak: 200 },
    target: 1,
    trackType: 'threw_6_to_non_neighbor',
  },
  // ── 43 ────────────────────────────────────────────────────────────────────
  {
    key: 'legendary_day',
    nameRu: 'Легендарный день',
    nameKk: 'Аңыздық күн',
    nameEn: 'Legendary Day',
    nameUk: 'Легендарний день',
    nameKa: 'ლეგენდარული დღე',
    nameAz: 'Əfsanəvi gün',
    nameUz: 'Afsonaviy Kun',
    descRu: 'Побей карту картой с таким же индексом и мастью 15 раз',
    descKk: 'Картаны сол индекс пен мастьтегі картамен 15 рет жеңіп шық',
    descEn: 'Beat a card with a card of the same rank and suit 15 times',
    descUk: 'Побий карту картою з таким же індексом і мастю 15 разів',
    descKa: 'ითამაშე 10 თამაში',
    descAz: 'Bu gün 1000 şanyrak qazan',
    descUz: 'Bir kunda barcha kunlik vazifalarni bajaring',
    reward: { shanyrak: 200 },
    target: 15,
    trackType: 'beat_same_rank_suit_15',
  },
];

export const DAILY_QUEST_MAP: Record<string, DailyQuestDef> = Object.fromEntries(
  DAILY_QUESTS.map(q => [q.key, q])
);

/** Moscow timezone offset in hours */
export const MOSCOW_UTC_OFFSET = 3;

/**
 * Returns the start of the current "Moscow day" as a UTC timestamp (ms).
 * Resets at 00:00 Moscow time = 21:00 UTC previous day.
 */
export function getMoscowDayStart(now: Date = new Date()): number {
  const utcMs = now.getTime();
  const moscowMs = utcMs + MOSCOW_UTC_OFFSET * 3600 * 1000;
  const moscowDate = new Date(moscowMs);
  // Midnight Moscow = floor to day
  const dayStart = new Date(Date.UTC(
    moscowDate.getUTCFullYear(),
    moscowDate.getUTCMonth(),
    moscowDate.getUTCDate(),
    0, 0, 0, 0,
  ));
  // Convert back to UTC
  return dayStart.getTime() - MOSCOW_UTC_OFFSET * 3600 * 1000;
}

/** Number of quests assigned per player per day */
export const DAILY_QUEST_COUNT = 4;
